[system]
port = ":10001"
OpenDES = false
DESkey = "wywmxxkj"
DESiv = "12345678"
MD5key = "Woyouxinxi666"
DESParam = "params"

[dbDefault]
dbHost = "rm-bp18387v5lkdvx7g4.mysql.rds.aliyuncs.com" #数据库连接地址
dbName = "locationtools"         #数据库名称
dbUser = "kingshardadmin"            #数据库用户名
dbPasswd = "Kwbd7246005c039789d9"  #数据库密码
dbPort = "3306"               #数据库端口号
dbOpenconns_max = 20           #最大连接数
dbIdleconns_max = 1            #最大空闲连接
dbType = "mysql"